# Generated by Django 5.2.8 on 2025-11-22 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('commit_hash', models.CharField(max_length=40)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.repository')),
            ],
        ),
        migrations.CreateModel(
            name='GitObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha1', models.CharField(db_index=True, max_length=40)),
                ('type', models.CharField(choices=[('blob', 'Blob'), ('tree', 'Tree'), ('commit', 'Commit')], max_length=10)),
                ('data', models.BinaryField()),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utils_app.repository')),
            ],
            options={
                'unique_together': {('repo', 'sha1')},
            },
        ),
    ]
